services:
  fin-assistant-mcp:
    auth:
      strategy: obo_required
      target_audience: "account"  # Updated to match TOKEN_AUDIENCE from docker-compose
      keycloak_server_url: "http://localhost:8080"
      realm: "BridgeMCP" 
      client_id: "fin-mcp-server"
      token_issuer: "http://localhost:8080/realms/BridgeMCP"
      required_scopes: []  # Remove scope requirement for now
      # Alternative: Use standard OAuth scopes: ["openid", "profile", "email"]
      custom_headers:
        X-Service-Name: "mcp-gateway"
        X-Version: "1.0.0"
        Accept: "application/json"
        Content-Type: "application/json"
      jwks_cache_ttl: 3600
      clock_skew_tolerance: 300
    description: Financial Statement Analysis MCP Server with OAuth 2.0 authentication
    enabled: true
    endpoint: http://localhost:3000
    health_check_path: /health
    name: Financial Assistant MCP
    timeout: 30
    transport: http
    version: "1.0.0"
  example-mcp-server:
    auth:
      strategy: obo_required
    description: A sample MCP server for demonstration
    enabled: true
    endpoint: http://example-mcp-server:3000
    health_check_path: /health
    name: Example MCP Server
    timeout: 30
    transport: http
  legacy-passthrough-server:
    auth:
      custom_headers:
        X-Gateway: mcp-gateway
      required_scopes:
      - legacy:access
      - mcp:call
      strategy: passthrough
    description: Legacy server that accepts user tokens directly
    enabled: true
    endpoint: https://legacy.company.com
    health_check_path: /health
    name: Legacy Passthrough Server
    timeout: 45
    transport: http
  local-mcp-server:
    auth:
      strategy: obo_required
    command:
    - python
    - -m
    - my_mcp_server
    description: Local MCP server using stdio transport
    enabled: true
    endpoint: local-stdio-server
    name: Local MCP Server
    transport: stdio
    working_directory: /path/to/mcp/server
  secure-analytics-server:
    auth:
      custom_headers:
        X-Service-Name: mcp-gateway
        X-Version: 1.0.0
      required_scopes:
      - analytics:read
      - mcp:call
      strategy: obo_required
      target_audience: analytics-api
    description: Analytics server requiring OBO token exchange
    enabled: true
    endpoint: https://analytics.company.com
    health_check_path: /health
    name: Secure Analytics Server
    timeout: 30
    transport: http
